title: Elena Sirotkina
url: "https://elenasirotkina.rocks"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #
#google_analytics: "G-41CDFP8VXH" 

footer: yes
footer_url: ""
footer_text: "(C) Elena Sirotkina | Assistant Professor / Faculty Fellow at CDS, NYU"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "CV"
   link: "resume.pdf"
 - name: "Email"
   link: "email" 
