title: Elena Sirotkina
url: "https://esirotkina.github.io/main/"
baseurl: "/main"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #
#google_analytics: "G-41CDFP8VXH"

footer: yes
footer_url: ""
footer_text: "(C) Elena Sirotkina | Page is designed by Ankit Sultana. I've modeled my website content after Polina Zabrodskaya's website, who is a brilliant and talented professional. Just like me one day."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/main/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact" 
